name: gradle-build

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ '**' ]

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0

      - name: Run Build
        run: gradle clean build --parallel

  pitest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0

      - name: Run Build
        run: gradle pitest pitestReportAggregate --parallel
รณ
      - name: Publish Pitest Report
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/reports/pitest
          full_commit_message: Publishing pitest reports for ${GITHUB_SHA}
