name: gradle-build

on:
  pull_request:
    branches: [ '**' ]

jobs:

  cancel:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'gradle'

      - name: Run Build
        run: gradle clean build --parallel

      - name: Run Build
        run: gradle pitest pitestReportAggregate --parallel

      - name: Publish Pitest Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/reports/pitest
          exclude_assets: '.github,*.xml'
          full_commit_message: Publishing pitest reports for ${GITHUB_SHA}
