name: gradle-build

on:
  pull_request:
    branches: [ '**' ]

jobs:

  cancel:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          cache: 'gradle'

      - name: Run Build
        run: gradle clean build pitest-github --parallel
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
